// Package plugins provides lifecycle plugins for markata-go.
package plugins

import (
	"bufio"
	"bytes"
	"fmt"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/WaylonWalker/markata-go/pkg/lifecycle"
)

const (
	nginxRedirectsFilename = "redirects.conf"
	nginxGeneratedHeader   = "# Generated by markata-go. Do not edit.\n"
)

// Redirect represents a single URL redirect rule.
type Redirect struct {
	// Original is the source path (the old URL).
	Original string

	// New is the destination path (the new URL).
	New string
}

// RedirectsConfig holds configuration for the redirects plugin.
type RedirectsConfig struct {
	// RedirectsFile is the path to the _redirects file.
	// Default: "static/_redirects"
	RedirectsFile string

	// RedirectTemplate is an optional path to a custom template.
	// If empty, the default template is used.
	RedirectTemplate string
}

// RedirectsPlugin generates nginx-native redirects plus optional HTML fallback
// pages from a _redirects file.
type RedirectsPlugin struct {
	config       RedirectsConfig
	htmlFallback bool
}

// NewRedirectsPlugin creates a new RedirectsPlugin with default configuration.
func NewRedirectsPlugin() *RedirectsPlugin {
	return &RedirectsPlugin{
		config: RedirectsConfig{
			RedirectsFile: "static/_redirects",
		},
		htmlFallback: true,
	}
}

// Name returns the unique name of the plugin.
func (p *RedirectsPlugin) Name() string {
	return "redirects"
}

// Configure loads plugin configuration from the manager.
func (p *RedirectsPlugin) Configure(m *lifecycle.Manager) error {
	config := m.Config()
	if config.Extra == nil {
		return nil
	}

	// Look for redirects configuration in [markata-go.redirects] or [redirects]
	var redirectsConfig map[string]interface{}

	// Try markata-go.redirects first
	if markataGo, ok := config.Extra["markata-go"].(map[string]interface{}); ok {
		if rc, ok := markataGo["redirects"].(map[string]interface{}); ok {
			redirectsConfig = rc
		}
	}

	// Fall back to top-level redirects
	if redirectsConfig == nil {
		if rc, ok := config.Extra["redirects"].(map[string]interface{}); ok {
			redirectsConfig = rc
		}
	}

	if redirectsConfig == nil {
		return nil
	}

	// Extract configuration values
	if rf, ok := redirectsConfig["redirects_file"].(string); ok && rf != "" {
		p.config.RedirectsFile = rf
	}
	if rt, ok := redirectsConfig["redirect_template"].(string); ok && rt != "" {
		p.config.RedirectTemplate = rt
	}
	if hf, ok := redirectsConfig["html_fallback"].(bool); ok {
		p.htmlFallback = hf
	}

	return nil
}

// Write generates nginx redirect rules and, by default, HTML fallback pages for
// each supported redirect rule.
func (p *RedirectsPlugin) Write(m *lifecycle.Manager) error {
	config := m.Config()
	outputDir := config.OutputDir

	// Skip redirect generation in fast mode - redirects don't change during content editing.
	if fast, ok := config.Extra["fast_mode"].(bool); ok && fast {
		return nil
	}

	// Read the redirects file.
	redirectsContent, err := os.ReadFile(p.config.RedirectsFile)
	if err != nil {
		if os.IsNotExist(err) {
			// If this plugin generated a native config on an earlier build, remove it
			// when the redirects source goes away. Never delete an unrecognized file.
			if cleanupErr := p.removeGeneratedNginxRedirects(outputDir); cleanupErr != nil {
				return fmt.Errorf("removing stale nginx redirects: %w", cleanupErr)
			}
			return nil
		}
		return fmt.Errorf("reading redirects file %s: %w", p.config.RedirectsFile, err)
	}

	// Parse redirect rules and refresh the native nginx artifact. A source that
	// becomes empty clears an existing generated include, while a fresh empty
	// source does not create an unnecessary redirects.conf file.
	redirects := p.parseRedirects(string(redirectsContent))
	if err := p.writeNginxRedirects(redirects, outputDir); err != nil {
		return fmt.Errorf("writing nginx redirects: %w", err)
	}

	if len(redirects) == 0 {
		return nil
	}

	if p.htmlFallback {
		// Load template.
		tmpl, err := p.loadTemplate()
		if err != nil {
			return fmt.Errorf("loading redirect template: %w", err)
		}

		// Generate redirect pages.
		for _, redirect := range redirects {
			if err := p.writeRedirect(redirect, tmpl, outputDir, config); err != nil {
				// Log error but continue with other redirects.
				log.Printf("warning: failed to write redirect for %s: %v", redirect.Original, err)
			}
		}
	}

	return nil
}

// parseRedirects parses the redirects file content into redirect rules.
func (p *RedirectsPlugin) parseRedirects(content string) []Redirect {
	var redirects []Redirect

	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines
		if line == "" {
			continue
		}

		// Skip comments
		if strings.HasPrefix(line, "#") {
			continue
		}

		// Skip wildcards (not supported by the HTML fallback or generated exact-match nginx rules)
		if strings.Contains(line, "*") {
			continue
		}

		// Split by whitespace
		parts := strings.Fields(line)
		if len(parts) < 2 {
			// Malformed line, skip
			continue
		}

		original := parts[0]
		newPath := parts[1]

		// Validate source path starts with /
		if !strings.HasPrefix(original, "/") {
			continue
		}

		// Validate destination: must be absolute path or external URL
		if !strings.HasPrefix(newPath, "/") &&
			!strings.HasPrefix(newPath, "http://") &&
			!strings.HasPrefix(newPath, "https://") {
			continue
		}

		redirects = append(redirects, Redirect{
			Original: original,
			New:      newPath,
		})
	}

	return redirects
}

// writeNginxRedirects writes exact-match nginx location rules to redirects.conf.
func (p *RedirectsPlugin) writeNginxRedirects(redirects []Redirect, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory %s: %w", outputDir, err)
	}

	outputPath := filepath.Join(outputDir, nginxRedirectsFilename)
	if len(redirects) == 0 {
		if _, err := os.Stat(outputPath); err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return fmt.Errorf("stating existing %s: %w", outputPath, err)
		}
	}
	if err := ensureGeneratedNginxRedirectsWritable(outputPath); err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString(nginxGeneratedHeader)
	buf.WriteString("# Include this file inside an nginx server block.\n\n")

	for _, redirect := range redirects {
		fmt.Fprintf(&buf, "location = %s {\n", quoteNginxString(redirect.Original))
		fmt.Fprintf(&buf, "    return 301 %s;\n", quoteNginxString(redirect.New))
		buf.WriteString("}\n\n")
	}

	//nolint:gosec // G306: generated nginx configuration is intended to be web-server readable
	if err := os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	return nil
}

// ensureGeneratedNginxRedirectsWritable prevents the plugin from silently
// clobbering a redirects.conf copied from static assets or managed by the user.
func ensureGeneratedNginxRedirectsWritable(outputPath string) error {
	content, err := os.ReadFile(outputPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("reading existing %s: %w", outputPath, err)
	}
	if !bytes.HasPrefix(content, []byte(nginxGeneratedHeader)) {
		return fmt.Errorf("refusing to overwrite user-managed %s; remove or rename it to use generated nginx redirects", outputPath)
	}
	return nil
}

// removeGeneratedNginxRedirects removes a stale redirects.conf only when it is
// recognizable as an artifact owned by this plugin. A user-authored file at the
// same path is left untouched.
func (p *RedirectsPlugin) removeGeneratedNginxRedirects(outputDir string) error {
	outputPath := filepath.Join(outputDir, nginxRedirectsFilename)
	content, err := os.ReadFile(outputPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("reading %s: %w", outputPath, err)
	}
	if !bytes.HasPrefix(content, []byte(nginxGeneratedHeader)) {
		return nil
	}
	if err := os.Remove(outputPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing %s: %w", outputPath, err)
	}
	return nil
}

// quoteNginxString quotes a value for nginx configuration and prevents
// accidental variable interpolation in generated redirect rules.
func quoteNginxString(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`$`, `\$`,
	)
	return `"` + replacer.Replace(value) + `"`
}

// loadTemplate loads the redirect template (custom or default).
func (p *RedirectsPlugin) loadTemplate() (*template.Template, error) {
	if p.config.RedirectTemplate != "" {
		// Load custom template
		content, err := os.ReadFile(p.config.RedirectTemplate)
		if err != nil {
			log.Printf("warning: failed to read custom redirect template %s: %v, using default", p.config.RedirectTemplate, err)
			return template.New("redirect").Parse(defaultRedirectTemplate)
		}
		tmpl, err := template.New("redirect").Parse(string(content))
		if err != nil {
			log.Printf("warning: failed to parse custom redirect template %s: %v, using default", p.config.RedirectTemplate, err)
			return template.New("redirect").Parse(defaultRedirectTemplate)
		}
		return tmpl, nil
	}

	return template.New("redirect").Parse(defaultRedirectTemplate)
}

// writeRedirect writes a single redirect page.
func (p *RedirectsPlugin) writeRedirect(redirect Redirect, tmpl *template.Template, outputDir string, config *lifecycle.Config) error {
	// Calculate output path: output_dir/original_path/index.html
	// Strip leading slash and create directory structure
	relativePath := strings.TrimPrefix(redirect.Original, "/")
	if relativePath == "" {
		// Can't redirect from root
		return nil
	}

	// Clean the path and validate no path traversal
	cleanPath := filepath.Clean(relativePath)
	if strings.Contains(cleanPath, "..") {
		return fmt.Errorf("path traversal detected in redirect source: %s", redirect.Original)
	}

	postDir := filepath.Join(outputDir, cleanPath)

	// Check if a file already exists at this path (e.g., rss.xml is a file, not a directory)
	// If so, skip the redirect as the content is already being served
	if info, err := os.Stat(postDir); err == nil && !info.IsDir() {
		// File exists at this path, skip redirect
		return nil
	}

	// Create directory
	if err := os.MkdirAll(postDir, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", postDir, err)
	}

	// Prepare template data
	data := struct {
		Original string
		New      string
		Config   *lifecycle.Config
	}{
		Original: redirect.Original,
		New:      redirect.New,
		Config:   config,
	}

	// Render template
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Write index.html
	outputPath := filepath.Join(postDir, "index.html")
	//nolint:gosec // G306: HTML output files need 0644 for web serving
	if err := os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	return nil
}

// hashContent creates a simple deterministic hash of content.
func hashContent(content []byte) uint64 {
	var hash uint64 = 5381
	for _, b := range content {
		hash = ((hash << 5) + hash) + uint64(b)
	}
	return hash
}

// defaultRedirectTemplate is the built-in HTML template for redirect pages.
const defaultRedirectTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Refresh" content="0; url='{{ .New }}'" />
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="canonical" href="{{ .New }}" />
  <meta name="description" content="{{ .Original }} has been moved to {{ .New }}." />
  <title>{{ .Original }} has been moved to {{ .New }}</title>
  <style>
    html {
      font-family: system-ui, sans-serif;
      background: #1f2022;
      color: #eefbfe;
    }
    body {
      margin: 5rem auto;
      max-width: 800px;
      padding: 0 1rem;
    }
    a {
      color: #fb30c4;
      text-decoration-color: #e1bd00c9;
    }
    code {
      background: #2a2a2e;
      padding: 0.2em 0.4em;
      border-radius: 3px;
    }
  </style>
</head>
<body>
  <h1>Page Moved</h1>
  <p>
    <code>{{ .Original }}</code> has moved to
    <a href="{{ .New }}">{{ .New }}</a>
  </p>
</body>
</html>`

// Priority returns the plugin priority for the given stage.
// Redirects should run late in the write stage, after content is written.
func (p *RedirectsPlugin) Priority(stage lifecycle.Stage) int {
	if stage == lifecycle.StageWrite {
		return lifecycle.PriorityLate
	}
	return lifecycle.PriorityDefault
}

// SetConfig allows setting the plugin configuration directly (useful for testing).
func (p *RedirectsPlugin) SetConfig(config RedirectsConfig) {
	p.config = config
}

// GetConfig returns the current plugin configuration.
func (p *RedirectsPlugin) GetConfig() RedirectsConfig {
	return p.config
}

// HTMLFallbackEnabled reports whether HTML redirect pages are generated in
// addition to redirects.conf.
func (p *RedirectsPlugin) HTMLFallbackEnabled() bool {
	return p.htmlFallback
}

// Ensure RedirectsPlugin implements the required interfaces.
var (
	_ lifecycle.Plugin          = (*RedirectsPlugin)(nil)
	_ lifecycle.ConfigurePlugin = (*RedirectsPlugin)(nil)
	_ lifecycle.WritePlugin     = (*RedirectsPlugin)(nil)
	_ lifecycle.PriorityPlugin  = (*RedirectsPlugin)(nil)
)
