{{- if and .Values.markataEncryption.secretName .Values.markataEncryption.sealedSecret.enabled .Values.markataEncryption.sealedSecret.encryptedData.MARKATA_GO_ENCRYPTION_KEY_DEFAULT }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.markataEncryption.secretName | quote }}
  namespace: "{{ include "markata-notes.namespace" . }}"
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: {{ .Values.markataEncryption.sealedSecret.encryptedData.MARKATA_GO_ENCRYPTION_KEY_DEFAULT | quote }}
  template:
    metadata:
      name: {{ .Values.markataEncryption.secretName | quote }}
      namespace: "{{ include "markata-notes.namespace" . }}"
    type: Opaque
{{- end }}
{{- if and .Values.aws.existingSecretName .Values.aws.sealedSecret.enabled .Values.aws.sealedSecret.encryptedData }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.aws.existingSecretName | quote }}
  namespace: "{{ include "markata-notes.namespace" . }}"
spec:
  encryptedData:
    {{- range $key, $value := .Values.aws.sealedSecret.encryptedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.aws.existingSecretName | quote }}
      namespace: "{{ include "markata-notes.namespace" . }}"
    type: Opaque
{{- end }}
