{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "markata-notes.serviceAccountName" . }}"
  namespace: "{{ include "markata-notes.namespace" . }}"
  labels:
    {{- include "markata-notes.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
