// Package configdocs extracts struct field doc comments from pkg/models so
// the serve settings sidebar can describe every config option.
package configdocs

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Extract returns "TypeName.FieldName" -> doc text for every documented
// struct field in the non-test Go files of dir.
func Extract(dir string) (map[string]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	docs := map[string]string{}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		ast.Inspect(file, func(n ast.Node) bool {
			spec, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			st, ok := spec.Type.(*ast.StructType)
			if !ok {
				return true
			}
			for _, field := range st.Fields.List {
				text := ""
				if field.Doc != nil {
					text = field.Doc.Text()
				} else if field.Comment != nil {
					text = field.Comment.Text()
				}
				text = strings.Join(strings.Fields(text), " ")
				if text == "" {
					continue
				}
				for _, ident := range field.Names {
					if ident.IsExported() {
						docs[spec.Name.Name+"."+ident.Name] = text
					}
				}
			}
			return true
		})
	}
	return docs, nil
}

// Render returns gofmt-ed Go source declaring docs as settingDocs in pkg.
func Render(pkg string, docs map[string]string) ([]byte, error) {
	keys := make([]string, 0, len(docs))
	for key := range docs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ../../internal/configdocs/gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// settingDocs maps \"Type.Field\" in pkg/models to the field's doc comment.\n")
	b.WriteString("var settingDocs = map[string]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(key), strconv.Quote(docs[key]))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
